# phpのインストール
---  
  - name: phpをインストール
    yum: name={{ item }} state=present enablerepo=remi-php71
    with_items:
      - php 
      - php-devel 
      - php-process
      - php-pdo 
      - php-pgsql
      - php-mbstring
      - php-mcrypt
      - php-xdebug
      - php-common
      - php-opcache
    tags:
      - php